name: Annapolis_Updates
favicon: null
layout_spectrum: 0.10401513846591115
typography_spectrum: 0.7009563245810568
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3603176490869373
  lightness: 0.06306553119793534
  saturation: 0.47945620864629745
  rhythmicContrast: 0.941855694167316
purpose: []
